Ee 162
bcgov/eagle-helper-pods pull request #41
Opened 2020-04-23 19:03 UTC by MaxWardle

2020-04-23 22:25 UTC, mtCarto requested changes

2020-04-23 22:25 UTC, mtCarto commented on openshift/setup-teardown/setup-all.sh
> +# deployApi $(<${API_ARGS_FILE});
Do these need to be uncommented?

2020-04-23 22:30 UTC, MaxWardle commented on openshift/setup-teardown/setup-all.sh
> +# deployApi $(<${API_ARGS_FILE});
yes, thanks, I'll fix that

2020-04-23 22:54 UTC, mtCarto approved these changes

2020-04-27 23:06 UTC, CEBergin approved these changes

2020-05-05 21:34 UTC, merged